FROM golang:trixie AS builder

WORKDIR /src
COPY . .

RUN apt-get update
RUN apt-get install -y --no-install-recommends gcc pkgconf libpcsclite-dev
RUN make V=1 build

FROM smallstep/step-cli:trixie

COPY --from=builder /src/bin/step-kms-plugin /usr/local/bin/step-kms-plugin

USER root
RUN apt-get update
RUN apt-get install -y --no-install-recommends pcscd libpcsclite1 p11-kit p11-kit-modules
USER step

CMD ["/bin/bash"]
