FROM golang AS builder

WORKDIR /src
COPY . .

RUN apt-get update && apt-get upgrade
RUN apt-get install -y --no-install-recommends \
               gcc pkgconf libpcsclite-dev
RUN make V=1 build

FROM smallstep/step-cli:debian

COPY --from=builder /src/bin/step-kms-plugin /usr/local/bin/step-kms-plugin

USER root
RUN apt-get install -y --no-install-recommends pcscd libpcsclite1
USER step

CMD ["/bin/bash"]
