name: CI

on:
  push:
    tags-ignore:
    - 'v*'
    branches:
    - "master"
  pull_request:
  workflow_call:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    uses: smallstep/workflows/.github/workflows/goCI.yml@56993c0fbbe5d7d4e3869cbd8f5411db38653e97
    with:
      os-dependencies: "libpcsclite-dev"
      run-codeql: true
    secrets: inherit

