name: Add Issues and PRs to Triage

on:
  issues:
    types:
      - opened
      - reopened
  pull_request_target:
    types:
      - opened
      - reopened

permissions:
  pull-requests: write
  issues: write

jobs:
  triage:
    uses: smallstep/workflows/.github/workflows/triage.yml@ccebb2a223f6f62936e26f5379492b199ef02331
    secrets: inherit
