name: Add Issues and PRs to Triage

on:
  issues:
    types:
      - opened
      - reopened
  pull_request_target:
    types:
      - opened
      - reopened

permissions:
  pull-requests: write
  issues: write

jobs:
  triage:
    uses: smallstep/workflows/.github/workflows/triage.yml@0b9040c4480f954b861c73da7937260da619fee5
    secrets: inherit
