name: Add Issues and PRs to Triage

on:
  issues:
    types:
      - opened
      - reopened
  pull_request_target:
    types:
      - opened
      - reopened

permissions:
  pull-requests: write
  issues: write

jobs:
  triage:
    uses: smallstep/workflows/.github/workflows/triage.yml@cdb139c9eadf8c1555d9a5a666c93c7cb4d97b31
    secrets: inherit
